actor:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 32
  dropout: 0.2
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


chameleon:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 64
  dropout: 0.8
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


squirrel:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  nhidden: 64
  dropout: 0.2
  patience: 100
  num_layers: 8
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


roman-empire:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.2
  patience: 100
  num_layers: 4
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


amazon-ratings:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 1
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


blogcatalog:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


flickr:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 128
  dropout: 0.8
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


photo:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 64
  dropout: 0.5
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True

arxiv:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 64
  dropout: 0.5
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True


wikics:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 1
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True

pubmed:
  lr: 0.0001
  l2_coef: 0.0001
  normalize: -1
  nhidden: 32
  dropout: 0.8
  patience: 100
  num_layers: 2
  num_heads: 1
  kernel: 'simple'
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
