pubmed:
  lr: 0.01
  l2_coef: 0.0001
  patience: 100


actor:
  lr: 0.001
  l2_coef: 0.0005
  patience: 100


chameleon:
  lr: 0.005
  l2_coef: 0.0001
  patience: 100


squirrel:
  lr: 0.001
  l2_coef: 0.001
  patience: 100


roman-empire:
  lr: 0.001
  l2_coef: 0.00001
  patience: 100


amazon-ratings:
  lr: 0.005
  l2_coef: 0.00005
  patience: 100


blogcatalog:
  lr: 0.001
  l2_coef: 0.
  patience: 100


flickr:
  lr: 0.001
  l2_coef: 0.
  patience: 100


photo:
  lr: 0.005
  l2_coef: 0.0005
  patience: 100


wikics:
  lr: 0.01
  l2_coef: 0.
  patience: 100
