pubmed:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.4
  dropout2: 0.1
  global_gating: True
  num_layers_input: 3
  patience: 100


actor:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.1
  dropout2: 0.2
  global_gating: False
  num_layers_input: 2
  patience: 100


chameleon:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.1
  global_gating: False
  num_layers_input: 2
  patience: 100


squirrel:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.1
  global_gating: False
  num_layers_input: 2
  patience: 100


roman-empire:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.4
  dropout2: 0.1
  global_gating: True
  num_layers_input: 2
  patience: 100


amazon-ratings:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.4
  dropout2: 0.1
  global_gating: False
  num_layers_input: 3
  patience: 100


blogcatalog:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.2
  global_gating: True
  num_layers_input: 1
  patience: 100


flickr:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.1
  global_gating: True
  num_layers_input: 1
  patience: 100


photo:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.2
  global_gating: True
  num_layers_input: 1
  patience: 100

arxiv:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.2
  global_gating: True
  num_layers_input: 1
  patience: 100


wikics:
  lr: 0.001
  l2_coef: 0.00005
  dropout: 0.8
  dropout2: 0.1
  global_gating: False
  num_layers_input: 2
  patience: 100
