actor:
  lr: 0.001
  l2_coef: 0.0005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 4
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.2
  gnn: "gcn"
  aggregate: "add"


chameleon:
  lr: 0.01
  l2_coef: 0.001
  normalize: -1
  nhidden: 32
  dropout: 0.8
  patience: 100
  num_layers: 8
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.8
  gnn: "gcn"
  aggregate: "add"


squirrel:
  lr: 0.01
  l2_coef: 0.0005
  normalize: -1
  nhidden: 64
  dropout: 0.8
  patience: 100
  num_layers: 8
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.8
  gnn: "gcn"
  aggregate: "add"


roman-empire:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.8
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.5
  gnn: "gcn"
  aggregate: "add"


amazon-ratings:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.2
  gnn: "gcn"
  aggregate: "add"


blogcatalog:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.2
  patience: 100
  num_layers: 2
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.8
  gnn: "gcn"
  aggregate: "add"


flickr:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 128
  dropout: 0.2
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.8
  gnn: "gcn"
  aggregate: "add"


photo:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 128
  dropout: 0.8
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.5
  gnn: "gcn"
  aggregate: "add"

arxiv:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  nhidden: 128
  dropout: 0.8
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.5
  gnn: "gcn"
  aggregate: "add"


wikics:
  lr: 0.01
  l2_coef: 0.00005
  normalize: -1
  nhidden: 128
  dropout: 0.5
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.5
  gnn: "gcn"
  aggregate: "add"

pubmed:
  lr: 0.001
  l2_coef: 0.01
  normalize: -1
  nhidden: 32
  dropout: 0.3
  patience: 100
  num_layers: 1
  num_heads: 1
  alpha: 0.5
  use_bn: True
  use_residual: True
  use_weight: True
  use_graph: True
  use_act: False
  graph_weight: 0.8
  gnn: "gcn"
  aggregate: "add"
