pubmed:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


actor:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


chameleon:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


squirrel:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


roman-empire:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.2
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


amazon-ratings:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


blogcatalog:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


flickr:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  dropout: 0.8
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


photo:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  dropout: 0.5
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8

arxiv:
  lr: 0.001
  l2_coef: 0.00005
  normalize: 1
  dropout: 0.5
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8


wikics:
  lr: 0.001
  l2_coef: 0.00005
  normalize: -1
  dropout: 0.5
  patience: 100
  nhidden: 512
  n_layers: 1
  n_hops: 8
