norms = {
    "chameleon": False,
    "squirrel": True,
    "actor": False,
    "flickr": True,
    "blogcatalog": True,
    "roman-empire": False,
    "amazon-ratings": True,
    "photo": True,
    "pubmed": True,
    "wikics": False,
    "arxiv": False,
    "products": False,
    "pokec": False,
}

feats = {
    "chameleon": 512,
    "squirrel": 512,
    "actor": 512,
    "photo": 256,
    "pubmed": 500,
    "roman-empire": 300,
    "amazon-ratings": 300,
    "flickr": 512,
    "blogcatalog": 512,
    "wikics": 300,
    "arxiv": 512,
    "products": 512,
    "pokec": 512,
}

l2_coefs = {
    "chameleon": 0.00005,
    "squirrel": 0.00005,
    "actor": 0.0000,
    "pubmed": 0.00005,
    "photo": 0.00005,
    "roman-empire": 0.00005,
    "amazon-ratings": 0.00005,
    "flickr": 0.00005,
    "blogcatalog": 0.00005,
    "wikics": 0.00005,
    "arxiv": 0.00005,
    "products": 0.00005,
    "pokec": 0.00005,
}

lrs = {
    "chameleon": 0.001,
    "squirrel": 0.001,
    "actor": 0.001,
    "pubmed": 0.001,
    "photo": 0.001,
    "roman-empire": 0.001,
    "amazon-ratings": 0.001,
    "flickr": 0.001,
    "blogcatalog": 0.001,
    "wikics": 0.001,
    "arxiv": 0.001,
    "products": 0.001,
    "pokec": 0.001,
}

ess = {
    "chameleon": 30,
    "squirrel": 50,
    "actor": 50,
    "pubmed": 100,
    "photo": 100,
    "roman-empire": 200,
    # "roman-empire": 100,
    "amazon-ratings": 100,
    "flickr": 100,
    "blogcatalog": 100,
    "wikics": 200,
    "arxiv": 200,
    "products": 200,
    "pokec": 200,
}

nas_dropouts = {
    "flickr": 0.8,
    "blogcatalog": 0.8,
    "chameleon": 0.8,
    "squirrel": 0.8,
    "actor": 0.0,
    "pubmed": 0.2,
    "photo": 0.4,
    "roman-empire": 0.2,
    "amazon-ratings": 0.0,
    "wikics": 0.2,
    "arxiv": 0.0,
    "products": 0.0,
    "pokec": 0.0,
}

nss_dropouts = {
    "flickr": 0.8,
    "blogcatalog": 0.8,
    "chameleon": 0.8,
    "squirrel": 0.8,
    "actor": 0.8,
    "pubmed": 0.8,
    "photo": 0.5,
    "roman-empire": 0.2,
    "amazon-ratings": 0.5,
    "wikics": 0.5,
    "arxiv": 0.8,
    "products": 0.8,
    "pokec": 0.8,
}

clf_dropouts = {
    "flickr": 0.9,
    "blogcatalog": 0.9,
    "chameleon": 0.9,
    "squirrel": 0.9,
    "actor": 0.9,
    "photo": 0.5,
    "pubmed": 0.9,
    "roman-empire": 0.2,
    "amazon-ratings": 0.9,
    "wikics": 0.9,
    "arxiv": 0.5,
    "products": 0.5,
    "pokec": 0.5,
}

n_hopss = {
    "chameleon": 64,
    "squirrel": 64,
    "actor": 1,
    "flickr": 10,
    "blogcatalog": 10,
    "roman-empire": 1,
    "amazon-ratings": 10,
    "photo": 10,
    "pubmed": 4,
    "wikics": 8,
    "arxiv": 10,
    "products": 10,
    "pokec": 10,
}

n_layerss = {
    "chameleon": 1,
    "squirrel": 1,
    "actor": 1,
    "flickr": 1,
    "blogcatalog": 1,
    # "roman-empire": 3,
    "roman-empire": 5,
    "amazon-ratings": 1,
    "photo": 1,
    "pubmed": 1,
    "wikics": 1,
    "arxiv": 1,
    "products": 1,
    "pokec": 1,
}

RNs = {
    "chameleon": "concat",
    "squirrel": "concat",
    "actor": "concat",
    "flickr": "concat",
    "blogcatalog": "concat",
    "roman-empire": "concat",
    "amazon-ratings": "concat",
    "pubmed": "concat",
    "photo": "concat",
    "wikics": "concat",
    "arxiv": "concat",
    "products": "concat",
    "pokec": "concat",
}

acts = {
    "chameleon": "relu",
    "squirrel": "relu",
    "actor": "relu",
    "flickr": "relu",
    "blogcatalog": "relu",
    "roman-empire": "relu",
    "amazon-ratings": "prelu",
    "photo": "relu",
    "pubmed": "relu",
    "wikics": "relu",
    "arxiv": "relu",
    "products": "relu",
    "pokec": "relu",
}

layer_norms = {
    "chameleon": True,
    "squirrel": True,
    "actor": True,
    "flickr": True,
    "blogcatalog": True,
    "roman-empire": True,
    "amazon-ratings": True,
    "photo": True,
    "pubmed": True,
    "wikics": True,
    "arxiv": True,
    "products": True,
    "pokec": True,
}

layer_norms_att = {
    "chameleon": False,
    "squirrel": False,
    "actor": True,
    "flickr": False,
    "blogcatalog": True,
    "roman-empire": False,
    "amazon-ratings": True,
    "photo": True,
    "pubmed": True,
    "wikics": False,
    "arxiv": False,
    "products": False,
    "pokec": False,
}

self_loop_attentive = {
    "chameleon": False,
    "squirrel": False,
    "actor": False,
    "flickr": False,
    "blogcatalog": False,
    "roman-empire": False,
    "amazon-ratings": False,
    "photo": False,
    "pubmed": False,
    "wikics": False,
    "arxiv": False,
    "products": False,
    "pokec": False,
}
